### ISSUE TITLE
Drone error?

### ISSUE THREAD

**Issue by SquidNeko** [TeamPneumatic/pnc-repressurized#1060]
### Describe the bug

Player timeouts after this happens in server log.

### How to reproduce the bug

I dont know. I dont even understand whats going on.

### Expected behavior

Things work?

### Additional details

[29.07 17:56:14] [Server] Negative index in crash report handler (0/20)
[29.07 17:56:14] [Server] Negative index in crash report handler (0/25)
[29.07 17:56:14] [Server] [Server thread/ERROR] [minecraft/EntityStorage]: An Entity type entity.pneumaticcraft.amadrone has thrown an exception trying to write state. It will not persist. Report this to the mod author
[29.07 17:56:14] [Server] net.minecraft.ReportedExceptionSaving entity NBT
[29.07 17:56:14] [Server] 	at net.minecraft.world.entity.Entity.m_20240_(Entity.java:1515) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:botania_xplat.mixins.json:AccessorEntity,pl:mixin:APP:botania_xplat.mixins.json:MixinEntity,pl:mixin:APP:the_bumblezone.mixins.json:entities.EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:wildbackport.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:ortus.mixins.json:EntityMixin,pl:mixin:APP:beyond_earth.mixin.json:EntityTick,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:expandability.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:notenoughcrashes.mixins.json:MixinEntity,pl:mixin:A}
[29.07 17:56:14] [Server] 	at net.minecraft.world.entity.Entity.m_20086_(Entity.java:1421) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:botania_xplat.mixins.json:AccessorEntity,pl:mixin:APP:botania_xplat.mixins.json:MixinEntity,pl:mixin:APP:the_bumblezone.mixins.json:entities.EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:wildbackport.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:ortus.mixins.json:EntityMixin,pl:mixin:APP:beyond_earth.mixin.json:EntityTick,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:expandability.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:notenoughcrashes.mixins.json:MixinEntity,pl:mixin:A}
[29.07 17:56:14] [Server] 	at net.minecraft.world.entity.Entity.m_20223_(Entity.java:1428) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:botania_xplat.mixins.json:AccessorEntity,pl:mixin:APP:botania_xplat.mixins.json:MixinEntity,pl:mixin:APP:the_bumblezone.mixins.json:entities.EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:wildbackport.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:ortus.mixins.json:EntityMixin,pl:mixin:APP:beyond_earth.mixin.json:EntityTick,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:expandability.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:notenoughcrashes.mixins.json:MixinEntity,pl:mixin:A}
[29.07 17:56:14] [Server] 	at net.minecraft.world.level.chunk.storage.EntityStorage.m_156565_(EntityStorage.java:94) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:classloading}
[29.07 17:56:14] [Server] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
[29.07 17:56:14] [Server] 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
[29.07 17:56:14] [Server] 	at net.minecraft.world.level.chunk.storage.EntityStorage.m_141971_(EntityStorage.java:91) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:classloading}
[29.07 17:56:14] [Server] 	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157512_(PersistentEntitySectionManager.java:218) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:classloading}
[29.07 17:56:14] [Server] 	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157578_(PersistentEntitySectionManager.java:292) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:classloading}
[29.07 17:56:14] [Server] 	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.forEach(LongOpenHashSet.java:802) ~[fastutil-8.5.6.jar%2330!/:?] {}
[29.07 17:56:14] [Server] 	at it.unimi.dsi.fastutil.longs.LongIterable.forEach(LongIterable.java:152) ~[fastutil-8.5.6.jar%2330!/:?] {re:computing_frames}
[29.07 17:56:14] [Server] 	at it.unimi.dsi.fastutil.longs.AbstractLongCollection.forEach(AbstractLongCollection.java:145) ~[fastutil-8.5.6.jar%2330!/:?] {re:computing_frames}
[29.07 17:56:14] [Server] 	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157554_(PersistentEntitySectionManager.java:287) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:classloading}
[29.07 17:56:14] [Server] 	at net.minecraft.server.level.ServerLevel.m_8643_(ServerLevel.java:705) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:wandering_trapper.mixins.json:ServerLevelMixin,pl:mixin:APP:the_bumblezone.mixins.json:world.ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
[29.07 17:56:14] [Server] 	at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:538) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:tetrapak.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:compactores.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[29.07 17:56:14] [Server] 	at net.minecraft.server.MinecraftServer.m_195514_(MinecraftServer.java:563) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:tetrapak.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:compactores.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[29.07 17:56:14] [Server] 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:868) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:tetrapak.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:compactores.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[29.07 17:56:14] [Server] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:tetrapak.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:compactores.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[29.07 17:56:14] [Server] 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23510!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:tetrapak.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:compactores.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[29.07 17:56:14] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
[29.07 17:56:14] [Server] Caused byjava.lang.NullPointerException

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.3.1-110

### Crash log

https://pastebin.com/3etwYuxA

**Comment by desht** [comment]
The amadrone "thrown an exception trying to write state" error is already fixed in dev, and fix will be in next release (very soon).

That error would not cause any kind of player timeout, though.

**Comment by desht** [comment]
Fixed in 3.4.0 release
