### ISSUE TITLE
Log spamming with errors

### ISSUE THREAD

**Issue by Zelioth** [TeamPneumatic/pnc-repressurized#1077]
### Describe the bug

Tons of log spams for errors and issues while launching and playing the game

### How to reproduce the bug

ummmm play the game haha. 

### Expected behavior

to function correctly

### Additional details

I'm playing on my mod pack "Friends United" version 2.0.6 it's on curse forge to reproduce 

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.1.0-128

### Crash log

https://pastebin.com/dzHG6zCW

**Comment by desht** [comment]
The log makes it clear that the PNC classes are only some of the many classes not found.  You have a broken instance here, almost certainly not due to PNC.  But without seeing the **entire** log file, I couldn't tell what.

**Comment by Zelioth** [comment]
[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/9438314/latest.log)

well here is my full log. I know I have a bunch of errors and im working on fixing like removing arclights and small ships. besides that if you can guide me how to fix the broken instance i would be greatful

**Comment by desht** [comment]
Yeah that looks like a real mess.  I can't really tell you which mod or mods are causing this, but a good place to start is with the first stacktrack logged, which is at line 906:

```
[20:20:16] [Thread-0/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$4590/0x0000000800d9c910@268f6157
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null
        at TRANSFORMER/forge@43.1.2/net.minecraftforge.network.simple.SimpleChannel.sendToServer(SimpleChannel.java:87)
        at TRANSFORMER/balm@4.5.3/net.blay09.mods.balm.forge.network.ForgeBalmNetworking.sendToServer(ForgeBalmNetworking.java:122)
        at TRANSFORMER/gravelminer@13.0.0/net.blay09.mods.gravelminer.client.GravelMinerClient.lambda$initialize$1(GravelMinerClient.java:22)
        at TRANSFORMER/balm@4.5.3/net.blay09.mods.balm.forge.event.ForgeBalmEvents.fireEventHandler(ForgeBalmEvents.java:50)
        at TRANSFORMER/balm@4.5.3/net.blay09.mods.balm.forge.event.ForgeBalmEvents.lambda$fireEventHandlers$0(ForgeBalmEvents.java:44)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at TRANSFORMER/balm@4.5.3/net.blay09.mods.balm.forge.event.ForgeBalmEvents.fireEventHandlers(ForgeBalmEvents.java:44)
        at TRANSFORMER/balm@4.5.3/net.blay09.mods.balm.forge.event.ForgeBalmEvents.fireEvent(ForgeBalmEvents.java:76)
        at TRANSFORMER/balm@4.5.3/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$7(ForgeBalmConfig.java:180)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at LAYER PLUGIN/javafmllanguage@1.19.2-43.1.2/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42)
        at LAYER PLUGIN/fmlcore@1.19.2-43.1.2/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:150)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.19.2-43.1.2/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:150)
        at LAYER PLUGIN/fmlcore@1.19.2-43.1.2/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
        at LAYER PLUGIN/fmlcore@1.19.2-43.1.2/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:147)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
```

Just bear in mind that any later errors (like the PNC one) are almost certainly caused by earlier ones.  It's essential to resolve earlier errors in the log before looking at later ones.
