### ISSUE TITLE
Heat Frame causes error

### ISSUE THREAD

**Issue by M3wP** [TeamPneumatic/pnc-repressurized#1125]
The Heat Frame is generating an error message although it seems to function correctly.

I am playing with Valhelsia modpack 5.0.12

![2023-01-14_20 03 08](https://user-images.githubusercontent.com/10175607/212468953-905bbaff-7c56-4649-b836-b244918d9b37.png)

**Comment by desht** [comment]
Is there anything in your log file (either server or client side) ?

Because that displayed error is completely useless.

**Comment by M3wP** [comment]
No, nothing in the log file I could see...

**Comment by desht** [comment]
Then ask the author of which mod that is (Jade? Hwyla?) to provide some better error detail, please.

**Comment by M3wP** [comment]
Wait, could this be what you're looking for?  Its not the Heat Frame but maybe its something similar?

I think its only actually generating the error once per game, maybe?  I can try creating a new world and see...




01/14/2023 - 19:54:43
***@***.***
java.lang.AbstractMethodError: Receiver class me.desht.pneumaticcraft.common.entity.semiblock.SpawnerAgitatorEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.network.chat.Component getDisplayName()' of interface me.desht.pneumaticcraft.api.semiblock.ISemiBlock.
      at ***@***.***/me.desht.pneumaticcraft.common.thirdparty.waila.SemiblockProvider$ComponentProvider.appendTooltip(SemiblockProvider.java:77)
      at ***@***.***/snownee.jade.impl.BlockAccessorImpl._gatherComponents(BlockAccessorImpl.java:120)
      at ***@***.***/snownee.jade.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:136)
      at ***@***.***/snownee.jade.util.ClientPlatformProxy.onClientTick(ClientPlatformProxy.java:138)
      at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
      at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
      at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
      at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
      at ***@***.***/net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:830)
      at ***@***.***/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1850)
      at ***@***.***/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078)
      at ***@***.***/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
      at ***@***.***/net.minecraft.client.main.Main.m_239872_(Main.java:212)
      at ***@***.***/net.minecraft.client.main.Main.main(Main.java:51)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
      at ***@***.***/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
      at ***@***.***/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
      at ***@***.***/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
      at ***@***.***/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
      at ***@***.***/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
      at ***@***.***/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
      at ***@***.***/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
      at ***@***.***/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
      at ***@***.***/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)





________________________________

**Comment by desht** [comment]
Yes, that could well be related, thanks.

**Comment by aoyawale** [comment]
hello, I'm getting this error. anyway I can fix this until a release?

**Comment by desht** [comment]
Fixed in latest 1.18/1.19 releases
