### ISSUE TITLE
Can't retrieve fluids using buckets

### ISSUE THREAD

**Issue by AlexiyOrlov** [TeamPneumatic/pnc-repressurized#1154]
### Describe the bug

I can't retrieve fluids from this mod's containers using buckets, it removes fluid from the container but leaves the bucket empty.

### How to reproduce the bug

Use an empty bucket on a tank or other fluid handler.

### Expected behavior

Receive fluid into bucket.

### Additional details

This is what happens in the console:
[Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@7c0b3087, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.sounds.SoundEvent.m_215668_(float)" because the return value of "net.minecraft.core.Holder.m_203334_()" is null
	at net.minecraft.server.level.ServerLevel.m_262808_(ServerLevel.java:889) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.world.level.Level.m_214150_(MixinLevel.java:395) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.world.level.Level.m_6263_(MixinLevel.java:401) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraftforge.fluids.FluidUtil.lambda$tryFillContainer$2(FluidUtil.java:141) ~[forge-1.19.3-44.1.17-universal.jar%23265!/:?]
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.19.3-44.1.17-universal.jar%23265!/:?]
	at net.minecraftforge.fluids.FluidUtil.tryFillContainer(FluidUtil.java:131) ~[forge-1.19.3-44.1.17-universal.jar%23265!/:?]
	at net.minecraftforge.fluids.FluidUtil.tryFillContainerAndStow(FluidUtil.java:233) ~[forge-1.19.3-44.1.17-universal.jar%23265!/:?]
	at me.desht.pneumaticcraft.common.util.FluidUtils.lambda$doFluidInteraction$0(FluidUtils.java:134) ~[pneumaticcraft-repressurized-1.19.3-5.0.0-23.jar%23241!/:1.19.3-5.0.0-23]
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.19.3-44.1.17-universal.jar%23265!/:?]
	at me.desht.pneumaticcraft.common.util.FluidUtils.lambda$doFluidInteraction$1(FluidUtils.java:130) ~[pneumaticcraft-repressurized-1.19.3-5.0.0-23.jar%23241!/:1.19.3-5.0.0-23]
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.19.3-44.1.17-universal.jar%23265!/:?]
	at me.desht.pneumaticcraft.common.util.FluidUtils.doFluidInteraction(FluidUtils.java:126) ~[pneumaticcraft-repressurized-1.19.3-5.0.0-23.jar%23241!/:1.19.3-5.0.0-23]
	at me.desht.pneumaticcraft.common.util.FluidUtils.tryFluidExtraction(FluidUtils.java:121) ~[pneumaticcraft-repressurized-1.19.3-5.0.0-23.jar%23241!/:1.19.3-5.0.0-23]
	at me.desht.pneumaticcraft.common.block.AbstractPneumaticCraftBlock.m_6227_(AbstractPneumaticCraftBlock.java:144) ~[pneumaticcraft-repressurized-1.19.3-5.0.0-23.jar%23241!/:1.19.3-5.0.0-23]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:730) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1056) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:773) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:756) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:750) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:735) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.19.3-20221207.122022-srg.jar%23260!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.3-5.0.0-23

**Comment by desht** [comment]
Honestly, this is not likely to be fixed in 1.19.3, an interim (and now dead-end) version

I will be doing a 1.19.4 port soon and I'll verify this works OK there.

**Comment by desht** [comment]
Actually a Forge issue, and fixed in the upcoming 1.20.1 release anyway...
