### ISSUE TITLE
Failed to process update information

### ISSUE THREAD

**Issue by bookerthegeek** [TeamPneumatic/pnc-repressurized#1373]
### Heyo!

Saw this in the log, thought you might want to know.

### How to reproduce the bug

- Install your mod
- Start MC
- Look at the log

### Expected behavior

For the update check to be successful

### Additional details

```
[09:41:43] [Forge Version Check/INFO] [ne.ne.fm.VersionChecker/]: [pneumaticcraft] Starting version check at https://raw.githubusercontent.com/TeamPneumatic/pnc-repressurized/1.21.1/release_info.json
[09:41:44] [Forge Version Check/WARN] [ne.ne.fm.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.fromJson(Gson.java:1238) ~[gson-2.10.1.jar%2399!/:?] {re:mixin}
	at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar%2399!/:?] {re:mixin}
	at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar%2399!/:?] {re:mixin}
	at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar%2399!/:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.VersionChecker$1.process(VersionChecker.java:167) ~[loader-4.0.31.jar%23174!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Unknown Source) [?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.VersionChecker$1.run(VersionChecker.java:105) [loader-4.0.31.jar%23174!/:4.0] {}
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar%2399!/:?] {}
	at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:182) ~[gson-2.10.1.jar%2399!/:?] {}
	at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144) ~[gson-2.10.1.jar%2399!/:?] {}
	at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar%2399!/:?] {re:mixin}
	... 6 more
```

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.2.3

**Comment by desht** [comment]
Thanks for spotting that, will be fixed in next release.

**Comment by desht** [comment]
Fixed in 8.2.13
