### ISSUE TITLE
Server exception: Exception Ticking World

### ISSUE THREAD

**Issue by Thunderflash121** [TeamPneumatic/pnc-repressurized#1387]
### Describe the bug

I get the Crash upon Server start when i uploaded my Saved ATm9 World from Version 0.3.5 to 1.0.0
In the old mod version the World runs fine and creating a new World in 1.0.0 works too . does somebody know how to fix that issue?

g---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2024-12-28 01:25:39
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 16 on Block{minecraft:water}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at net.minecraftforge.fluids.ForgeFlowingFluid.m_5804_(ForgeFlowingFluid.java:138) ~[forge-1.20.1-47.3.11-universal.jar%23930!/:?] {re:classloading}
	at net.minecraft.world.level.material.FluidState.m_76188_(FluidState.java:96) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,re:classloading}
	at me.desht.pneumaticcraft.common.heat.BlockHeatProperties.registerDefaultFluidValues(BlockHeatProperties.java:90) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.BlockHeatProperties.populateCustomHeatEntries(BlockHeatProperties.java:78) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.BlockHeatProperties.getCustomHeatEntry(BlockHeatProperties.java:51) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.behaviour.HeatBehaviourCustomTransition.initialize(HeatBehaviourCustomTransition.java:49) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.behaviour.HeatBehaviourManager.addHeatBehaviours(HeatBehaviourManager.java:75) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.HeatExchangerLogicTicking.initializeAsHull(HeatExchangerLogicTicking.java:67) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.block.entity.IHeatExchangingTE.lambda$initializeHullHeatExchangers$1(IHeatExchangingTE.java:91) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354) ~[?:?] {}
	at me.desht.pneumaticcraft.common.block.entity.IHeatExchangingTE.initializeHullHeatExchangers(IHeatExchangingTE.java:90) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.block.entity.AbstractPneumaticCraftBlockEntity.onLoad(AbstractPneumaticCraftBlockEntity.java:244) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.block.entity.AbstractAirHandlingBlockEntity.onLoad(AbstractAirHandlingBlockEntity.java:83) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraft.world.level.Level.m_46463_(Level.java:453) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:adastra.mixins.json:common.multipart.LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	PneumaticCraft: Repressurized (pneumaticcraft), Version: 6.0.18+mc1.20.1
		Issue tracker URL: https://github.com/TeamPneumatic/pnc-repressurized/issues
		at TRANSFORMER/pneumaticcraft@6.0.18+mc1.20.1/me.desht.pneumaticcraft.common.heat.BlockHeatProperties.registerDefaultFluidValues(BlockHeatProperties.java:90)
Stacktrace:
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at net.minecraftforge.fluids.ForgeFlowingFluid.m_5804_(ForgeFlowingFluid.java:138) ~[forge-1.20.1-47.3.11-universal.jar%23930!/:?] {re:classloading}
	at net.minecraft.world.level.material.FluidState.m_76188_(FluidState.java:96) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,re:classloading}
	at me.desht.pneumaticcraft.common.heat.BlockHeatProperties.registerDefaultFluidValues(BlockHeatProperties.java:90) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.BlockHeatProperties.populateCustomHeatEntries(BlockHeatProperties.java:78) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.BlockHeatProperties.getCustomHeatEntry(BlockHeatProperties.java:51) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.behaviour.HeatBehaviourCustomTransition.initialize(HeatBehaviourCustomTransition.java:49) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.behaviour.HeatBehaviourManager.addHeatBehaviours(HeatBehaviourManager.java:75) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.heat.HeatExchangerLogicTicking.initializeAsHull(HeatExchangerLogicTicking.java:67) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.block.entity.IHeatExchangingTE.lambda$initializeHullHeatExchangers$1(IHeatExchangingTE.java:91) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354) ~[?:?] {}
	at me.desht.pneumaticcraft.common.block.entity.IHeatExchangingTE.initializeHullHeatExchangers(IHeatExchangingTE.java:90) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.block.entity.AbstractPneumaticCraftBlockEntity.onLoad(AbstractPneumaticCraftBlockEntity.java:244) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at me.desht.pneumaticcraft.common.block.entity.AbstractAirHandlingBlockEntity.onLoad(AbstractAirHandlingBlockEntity.java:83) ~[pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar%23804!/:6.0.18+mc1.20.1] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraft.world.level.Level.m_46463_(Level.java:453) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:adastra.mixins.json:common.multipart.LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 7774
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,67,-288), Section: (at 0,3,0 in 15,4,-18; chunk contains blocks 240,-64,-288 to 255,319,-273), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 231945199 game time, 233045330 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 93553 (now: false), thunder time: 129763 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23925!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}

### How to reproduce the bug

Upload the saved world and try to start the server

### Expected behavior

a clean Server start

### Which Minecraft version are you using?

1.20.1

### Which version of PneumaticCraft: Repressurized are you using?

6.0.18

**Comment by desht** [comment]
PNC isn't doing anything out of the ordinary here, just trying to get an associated block from a fluid via a standard Minecraft method (`FluidState#createLegacyBlock()`).  Something (not PNC) is trying to pass 16 as the fluid level when getting the water block, which is definitely wrong.

Could be Ferrite Core doing something here, not certain. But definitely not PNC.

P.S. please don't just paste big stack traces directly into issue reports, paste sites exist for a reason.

**Comment by desht** [comment]
Update: confirmed not a PNC issue, see https://github.com/AllTheMods/ATM-9/issues/2175
