### ISSUE TITLE
Drone with Magnet crashed SevTech: Ages Server

### ISSUE THREAD

**Issue by SharkeyMyrl** [TeamPneumatic/pnc-repressurized#179]
---- Minecraft Crash Report ----
 
WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  CorePlugin (SmoothFont-1.12.2-1.15.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.176.jar)
  LoadingPlugin (noRecipeBook_v1.1.0formc1.12.2.jar)
  BNBGamingCore (BNBGamingCore-1.12.2-0.7.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  FarseekCoreMod (Farseek-1.12-2.2.5.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge
 
// Who set us up the TNT?
 
Time: 5/30/18 4:30 PM
Description: Ticking entity
 
java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
    at me.desht.pneumaticcraft.common.ai.DroneAIManager.pickupItemsIfMagnet(DroneAIManager.java:317)
    at me.desht.pneumaticcraft.common.ai.DroneAIManager.onUpdateTasks(DroneAIManager.java:328)
    at me.desht.pneumaticcraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:392)
    at net.minecraft.world.World.func_72866_a(World.java:1990)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
    at net.minecraft.world.World.func_72870_g(World.java:1952)
    at net.minecraft.world.World.func_72939_s(World.java:1756)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Unknown Source)

**Comment by desht** [comment]
Yeah, confirmed.  Calling a client-side method here, oops.

**Comment by desht** [comment]
Build 195 (or later) from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ should fix the crash (should be safe just to drop into Sevtech in place of the official version of PNC:R).  Will do a new official release soon.
