### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by DevTimur** [TeamPneumatic/pnc-repressurized#410]
### Minecraft Version
1.12.2
### Forge Version
2847
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.11.6-374
### Describe your problem, including steps to reproduce it
Randomly crashed
### Any other comments?

<details>
<summary>
<i>CRASHLOG</i>
</summary>
<p>
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at me.desht.pneumaticcraft.common.semiblock.SemiBlockManager.syncWithPlayers(SemiBlockManager.java:297)
	at me.desht.pneumaticcraft.common.semiblock.SemiBlockManager.onWorldTick(SemiBlockManager.java:281)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1000_SemiBlockManager_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)</p>
</details>

**Comment by desht** [comment]
Fixed in 0.11.8 release
