### ISSUE TITLE
Different issues being spammed in log

### ISSUE THREAD

**Issue by BedrockLegends** [TeamPneumatic/pnc-repressurized#455]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Mod Version pneumaticcraft-repressurized-1.15.2-1.1.0-3.jar

[15:11:04] [Server thread/ERROR]: Failed to reload data packs
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: Missing type, expected to find a string
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1467) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:77) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: com.google.gson.JsonSyntaxException: Missing type, expected to find a string
	at net.minecraft.util.JSONUtils.func_151200_h(SourceFile:112) ~[?:?]
	at me.desht.pneumaticcraft.common.recipes.amadron.AmadronOfferManager.lambda$loadRecipeOffers$8(AmadronOfferManager.java:279) ~[?:1.15.2-1.1.0-3]
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_251]
	at me.desht.pneumaticcraft.common.recipes.amadron.AmadronOfferManager.loadRecipeOffers(AmadronOfferManager.java:277) ~[?:1.15.2-1.1.0-3]
	at me.desht.pneumaticcraft.common.recipes.amadron.AmadronOfferManager.initOffers(AmadronOfferManager.java:163) ~[?:1.15.2-1.1.0-3]
	at me.desht.pneumaticcraft.common.recipes.amadron.AmadronOfferManager$ReloadListener.apply(AmadronOfferManager.java:330) ~[?:1.15.2-1.1.0-3]
	at me.desht.pneumaticcraft.common.recipes.amadron.AmadronOfferManager$ReloadListener.func_212853_a_(AmadronOfferManager.java:321) ~[?:1.15.2-1.1.0-3]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) ~[?:?]
	... 5 more

[15:11:36] [Render thread/ERROR]: Error while loading contents for book pneumaticcraft:book
java.lang.RuntimeException: Error building entry pneumaticcraft:base_concepts/cc_oc_integration
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:147) ~[?:1.15.2-1.2-33]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_251]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:143) ~[?:1.15.2-1.2-33]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:190) ~[?:1.15.2-1.2-33]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_251]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:114) ~[?:1.15.2-1.2-33]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:77) ~[?:1.15.2-1.2-33]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:36) ~[?:1.15.2-1.2-33]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1252) ~[?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) ~[?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:897) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.63.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry pneumaticcraft:base_concepts/cc_oc_integration page 10
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:223) ~[?:1.15.2-1.2-33]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:145) ~[?:1.15.2-1.2-33]
	... 29 more
Caused by: java.lang.RuntimeException: Unknown item ID: pneumaticcraft:plastic_mixer
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackFromString(ItemStackUtil.java:69) ~[?:1.15.2-1.2-33]
	at vazkii.patchouli.client.book.page.PageSpotlight.build(PageSpotlight.java:24) ~[?:1.15.2-1.2-33]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:220) ~[?:1.15.2-1.2-33]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:145) ~[?:1.15.2-1.2-33]
	... 29 more

**Comment by BedrockLegends** [comment]
[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/4571525/latest.log)

**Comment by BedrockLegends** [comment]
[crash-2020-05-04_00.29.01-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4572879/crash-2020-05-04_00.29.01-server.txt)

Another crash

**Comment by desht** [comment]
Can you try out build #4 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ ?

Should fix all the problems you've seen so far.

**Comment by BedrockLegends** [comment]
testing right now

**Comment by BedrockLegends** [comment]
Works, only thing I noticed is that your not using forge tag system. The following needs to be added

Reinforced Stone are missing from tag:forge:stone
Reinforced Stone Bricks are missing from tag:minecraft:stone_bricks
Reinforced Stair are missing from tag:minecraft:stairs
Reinforced slab & Reinforced Brick slab is missing from tag:minecraft:slabs
Reinforced Brick wall is missing from tag:minecraft:walls

@desht

**Comment by desht** [comment]
Hmm, thought I'd covered all those tags. I'll check those and get anything missing into the next release.

**Comment by desht** [comment]
Stair, wall and slab tags are in fact all present.  Not sure why you think they're missing.  You can see all the generated tags here: https://github.com/TeamPneumatic/pnc-repressurized/tree/1.15/src/generated/resources/data

`forge:stone` & `minecraft:stone_bricks` haven't been added to, but I can fix that for the next release.

**Comment by desht** [comment]
Should all be fixed in 1.1.1 release.  Also added Reinforced Stone & Reinforced Stone Bricks to respective tags.
