### ISSUE TITLE
Minigun corrupted my world

### ISSUE THREAD

**Issue by Zarandolph01** [TeamPneumatic/pnc-repressurized#513]
Gonna attach the log, do NOT complain. Not sending a file to you to read, you can read it here and save yourself, and myself, some time. I have tried removing the mod from the server files, after which, restarted the servers, did /fml confirm, and joined. It still crashed with the minigun GUI error. 

Caused by: java.lang.RuntimeException: Slot 34 not in valid range - [0,4)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:221) ~[?:?]
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73) ~[?:?]
	at me.desht.pneumaticcraft.common.item.ItemMinigun$MagazineHandler.getAmmo(ItemMinigun.java:233) ~[?:1.15.2-1.2.1-25]
	at me.desht.pneumaticcraft.common.item.ItemMinigun.getMinigun(ItemMinigun.java:130) ~[?:1.15.2-1.2.1-25]
	at me.desht.pneumaticcraft.common.item.ItemMinigun.func_77663_a(ItemMinigun.java:73) ~[?:1.15.2-1.2.1-25]
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:414) ~[?:?]
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:505) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361) ~[?:?]
	... 8 more

(That eight more it won't show me)

**Comment by desht** [comment]
Thought this looked familiar - also happened in #415 back in 1.12.2.  Guess that bug slipped through.  Your world is *not* corrupted - you just have a bit of bad NBT on the minigun (someone middle-clicked a slot in their own inventory while in the minigun magazine GUI) which the next build will detect and fix.  Your world is fine.

**Comment by desht** [comment]
Build 28 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ will fix your problem.  There will be a new release soon, but that build will get you going again.

**Comment by Zarandolph01** [comment]
I didn't know how to clear the item from the inventory, and yes, one of my friends on my server had middle clicked. Thankfully I had a backup from not too long ago, and not much had to be rebuilt. Lovely mod, and glad it's being kept up.

**Comment by Zarandolph01** [comment]
I'm using 1.15.2. Would the 1.15 version work?

**Comment by Zarandolph01** [comment]
Was asking a dumb question. Re-closing. Thanks for the fix!
