### ISSUE TITLE
NPE assembly controller GUI

### ISSUE THREAD

**Issue by purpleposeidon** [TeamPneumatic/pnc-repressurized#607]
```
java.lang.NullPointerException: Ticking screen
	at me.desht.pneumaticcraft.client.gui.GuiAssemblyController.addProblems(GuiAssemblyController.java:82) ~[?:1.16.1-2.2.0-29] {re:classloading}
	at me.desht.pneumaticcraft.client.gui.GuiPneumaticContainerBase.handleProblemsTab(GuiPneumaticContainerBase.java:406) ~[?:1.16.1-2.2.0-29] {re:classloading}
	at me.desht.pneumaticcraft.client.gui.GuiPneumaticContainerBase.func_231023_e_(GuiPneumaticContainerBase.java:392) ~[?:1.16.1-2.2.0-29] {re:classloading}
	at me.desht.pneumaticcraft.client.gui.GuiAssemblyController.func_231023_e_(GuiAssemblyController.java:52) ~[?:1.16.1-2.2.0-29] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$runTick$20(Minecraft.java:1424) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:421) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1423) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:928) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265] {}
```

On a server. Had ingredients for reinforced tubes, didn't have an output arm.

pneumaticcraft-repressurized-1.16.1-2.2.0-29.jar

**Comment by desht** [comment]
Interesting.  Looks like an impossible-to-reach situation (`te.isMachineMissing` should only be true if `te.missingMachine` is non-null, and the NPE is caused by `te.missingMachine` being null, but that branch of code is only executed if `te.isMachineMissing` is true).

**Comment by desht** [comment]
Can't actually reproduce this - my setup is below (note: Export IO Unit is missing, everything else is present; compressed iron block in the chest ready for convering to tubes).  This is on a dedicated server instance.

I can add a workaround for this NPE, but it would be nice to be able to reproduce the actual problem.  Can I see a screenshot of your setup?

![2020-09-09_08 51 27](https://user-images.githubusercontent.com/736831/92570419-cd723500-f279-11ea-9fd4-341917209f7a.png)
![2020-09-09_08 51 16](https://user-images.githubusercontent.com/736831/92570430-d236e900-f279-11ea-944f-7b9486a7d0d8.png)

**Comment by purpleposeidon** [comment]
Yeah, I'm not able to get it happening again.

**Comment by desht** [comment]
OK.  I can only guess something went wrong with syncing data to the client TE.  I'll add a sanity check in the GUI to avoid future crashes.

**Comment by desht** [comment]
Added checks in 2.2.2 & 2.4.0 releases to prevent this in future.
