### ISSUE TITLE
Internal Server error when player brushes Heat Sinks

### ISSUE THREAD

**Issue by stormtrooperxl** [TeamPneumatic/pnc-repressurized#641]
### Mod Version - 1.16.3-2.4.4-59

I have two flux compressors setup side by side with heatsinks covering two sides of each compressor. The bottom side of each compressor has a mekanism ultimate universal cable attached, the output side of each compressor has an advanced pressure tube attached. One compressor has a vortex tube on the top with a heat sink on top of the tube, the top spot on the second compressor is currently empty. 

When I touch one of the heat sinks and take damage it get kicked from the server and get a generic "Internal Server Error" message. I am then unable to log back in unless I teleport myself to another player via console.

![heatsink1](https://user-images.githubusercontent.com/56524217/97083657-8cdb3a80-15df-11eb-8566-b05c1946242e.png)

![heatsink2](https://user-images.githubusercontent.com/56524217/97083661-92d11b80-15df-11eb-97aa-203d150642da.png)

**Comment by desht** [comment]
Logs, please.  I can do nothing without a server log.

BTW, using Vortex Tubes to cool a compressor is a terrible idea.

**Comment by stormtrooperxl** [comment]
I have attached copies of the logs from both server side and client side.
[2020-10-24-server.log.gz](https://github.com/TeamPneumatic/pnc-repressurized/files/5433006/2020-10-24-server.log.gz)

[2020-10-24-Client.log.gz](https://github.com/TeamPneumatic/pnc-repressurized/files/5433007/2020-10-24-Client.log.gz)

**Comment by desht** [comment]
```
Caused by: java.lang.ArithmeticException: Division by zero
        at mekanism.api.math.FloatingLong.divideEquals(FloatingLong.java:329) ~[?:10.0.12]
        at mekanism.api.math.FloatingLong.divide(FloatingLong.java:471) ~[?:10.0.12]
        at mekanism.common.item.gear.ItemMekaSuitArmor.getDamageAbsorbed(ItemMekaSuitArmor.java:269) ~[?:10.0.12]
```

Looks like a bug with the Mekasuit to me.
