### ISSUE TITLE
[Bug] Client crash when loading into a multiplayer world

### ISSUE THREAD

**Issue by Ninezel** [TeamPneumatic/pnc-repressurized#752]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4

### Forge Version
35.1.37

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.10.2-148.jar

### Describe your problem, including steps to reproduce it
https://gist.github.com/Admiral-Sebastian/f79cd5a0479785afcb232e3e7754427b

### Any other comments?
happens when I login into my multiplayer world

**Comment by desht** [comment]
Can you make your full client log available somewhere please.  Because if that line's causing a crash, something probably went wrong much earlier on and left the HUD in an impossible state.

**Comment by Ninezel** [comment]
> Can you make your full client log available somewhere please. Because if that line's causing a crash, something probably went wrong much earlier on and left the HUD in an impossible state.

https://gist.github.com/Admiral-Sebastian/29d6baeefaaad1c509430aebbd09c363 here is the full client log

**Comment by desht** [comment]
Yep, as I thought:
```
java.lang.NullPointerException
        at org.orecruncher.lib.service.ModuleServiceManager.playerLogin(ModuleServiceManager.java:151)
        at org.orecruncher.lib.service.ModuleServiceManager.onPlayerLogin(ModuleServiceManager.java:142)
        at net.minecraftforge.eventbus.ASMEventHandler_1587_ModuleServiceManager_onPlayerLogin_LoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.client.ClientHooks.firePlayerLogin(ClientHooks.java:305)
        at net.minecraft.client.network.play.ClientPlayNetHandler.func_147282_a(ClientPlayNetHandler.java:387)
        at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:110)
        at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:18)
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191)
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:130)
        at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
        at net.minecraft.client.main.Main.main(Main.java:184)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

This is DynamicSurroundings and its `ClientPlayerNetworkEvent.LoggedInEvent` handler is crashing while handling client player login, preventing my login event handler from running.  My handler sets up the pneumatic helmet data that my HUD needs to run, and if it doesn't get to run, then... your game crashes.

I'll add some defensive code to the next release to prevent an outright crash in this situation, but the problem here is very definitely with Dynamic Surroundings.  You need to report this to them.

**Comment by desht** [comment]
Actually, looks like this is the same problem as https://github.com/OreCruncher/DynamicSurroundings/issues/685 and it looks like the mod author is aware and has a dev release to fix this.

**Comment by Ninezel** [comment]
Thank you 👍🏼
