### ISSUE TITLE
Game failed to load after crash: java.lang.IllegalArgumentException: Stack can not be invalid!

### ISSUE THREAD

**Issue by Protheus** [TeamPneumatic/pnc-repressurized#81]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
**1.12.2**

### Forge Version
**2566**

### Mod Version
**pneumaticcraft-repressurized-1.12.2-0.2.0-85**

### Describe your problem, including steps to reproduce it
**1.** Spawn Wither
**2.** Killed wither
**3.** the moment it died, the game stop responding
**4.** After reloading of the game the below game crash is given (see below for pastebin log)

java.lang.IllegalArgumentException: Stack can not be invalid!
    at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:481)
    at me.desht.pneumaticcraft.common.util.PneumaticCraftUtils.isSameOreDictStack(PneumaticCraftUtils.java:864)
    at me.desht.pneumaticcraft.common.EventHandlerPneumaticCraft.handleIronExplosions(EventHandlerPneumaticCraft.java:128)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1729_EventHandlerPneumaticCraft_handleIronExplosions_Detonate.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:517)
    at net.minecraft.world.Explosion.func_77278_a(Explosion.java:134)
    at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1168)
    at net.minecraft.entity.projectile.EntityWitherSkull.func_70227_a(EntityWitherSkull.java:118)
    at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
    at net.minecraft.world.World.func_72866_a(World.java:1986)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
    at net.minecraft.world.World.func_72870_g(World.java:1948)
    at net.minecraft.world.World.func_72939_s(World.java:1755)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Unknown Source)

### Any other comments?
**https://pastebin.com/YxBrYgCw**

**Comment by desht** [comment]
Could you try build 90 here and let me know if it helps?

http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/90/

**Comment by Protheus** [comment]
Yes that fixed the issue !.. thank you for this. Keep up the good work

**Comment by desht** [comment]
Good stuff. Closing now.
