### ISSUE TITLE
PneumaticCraft wasn't able to load third party content

### ISSUE THREAD

**Issue by bookerthegeek** [TeamPneumatic/pnc-repressurized#85]
## Heyo! ##
Saw this in the console. Thought you would want to know about it. Looking forward to playing with the mod. This did not cause a crash.
### Versions ###
 - Minecraft 1.12.2
 - forge-1.12.2-14.23.1.2575-universal.jar
 - pneumaticcraft-repressurized-1.12.2-0.2.0-85
### Relevant portion of the log ###
```
[16:59:01] [main/ERROR] [pneumaticcraft]: PneumaticCraft wasn't able to load third party content from the third party class class me.desht.pneumaticcraft.common.thirdparty.forestry.Forestry in the Init phase!
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: java.lang.NullPointerException: Fluid can't be null!
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at me.desht.pneumaticcraft.common.PneumaticCraftAPIHandler.registerFuel(PneumaticCraftAPIHandler.java:93)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at me.desht.pneumaticcraft.common.thirdparty.forestry.Forestry.init(Forestry.java:11)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager.init(ThirdPartyManager.java:117)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at me.desht.pneumaticcraft.PneumaticCraftRepressurized.onInit(PneumaticCraftRepressurized.java:146)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:719)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:59:01] [main/INFO] [STDERR]: [me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager:init:120]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
[Complete Startup Log](https://gist.github.com/bookerthegeek/7bcce558a695d1784e0964914b0f14ab)

**Comment by MineMaarten** [comment]
Thanks for the detailed report! Should be fixed
