### ISSUE TITLE
Missing manual pages

### ISSUE THREAD

**Issue by SatyrRex** [TeamPneumatic/pnc-repressurized#888]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
36.2.2

### Mod Version
2.13.5-218

### Describe your problem, including steps to reproduce it
When opening the PNC book to various pages, all I get is a blank PNC-themed page, without any text or images. Happens both when reading the book directly, and pressing I over a widget piece in the Programmer.
![Untitled](https://user-images.githubusercontent.com/20699503/131233423-950c0332-ac89-4758-a9d5-0cc90b766886.png)

**Comment by SatyrRex** [comment]
Oh, Patchouli is v. 1.16.4-53.1

**Comment by desht** [comment]
Looks like Patchouli isn't loading the page data properly for you. Can you check your latest.log for errors please?

**Comment by SatyrRex** [comment]
I did find this

[17:16:57] [Render thread/ERROR]: Error while loading contents for book pneumaticcraft:book
java.lang.RuntimeException: Error building entry pneumaticcraft:base_concepts/heat
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:141) ~[?:1.16.4-53.1]
	at vazkii.patchouli.client.book.BookContents$$Lambda$21655/1395402541.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$Values.forEach(HashMap.java:972) ~[?:1.8.0_51]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:137) [?:1.16.4-53.1]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) [?:1.16.4-53.1]
	at vazkii.patchouli.common.book.BookRegistry$$Lambda$21645/665704469.accept(Unknown Source) [?:1.16.4-53.1]
	at java.util.HashMap$Values.forEach(HashMap.java:972) [?:1.8.0_51]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:105) [?:1.16.4-53.1]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) [?:1.16.4-53.1]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) [?:1.16.4-53.1]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.handler$zii000$patchouli_onSync(SourceFile:518) [?:?]
	at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1275) [?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) [?:?]
	at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$20760/844406500.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:179) [?:0.12.1.128]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:52) [?:0.12.1.128]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:36) [?:0.12.1.128]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) [?:0.12.1.128]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) [?:0.12.1.128]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71) [?:0.12.1.128]
	at mezz.jei.load.PluginLoader.lambda$new$3(PluginLoader.java:108) [?:7.7.1.121]
	at mezz.jei.load.PluginLoader$$Lambda$21468/606832299.accept(Unknown Source) [?:7.7.1.121]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) [?:7.7.1.121]
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:108) [?:7.7.1.121]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69) [?:7.7.1.121]
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) [?:7.7.1.121]
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) [?:7.7.1.121]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) [?:7.7.1.121]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$17036/1340473684.accept(Unknown Source) [?:7.7.1.121]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2951/554055165.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2583/1167009361.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:711) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$20760/844406500.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.2.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/1976503781.call(Unknown Source) [forge-1.16.5-36.2.2.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry pneumaticcraft:base_concepts/heat page 5
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:224) ~[?:1.16.4-53.1]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16.4-53.1]
	... 65 more
Caused by: java.lang.RuntimeException: Unknown item ID: toughasnails:thermometer
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackFromString(ItemStackUtil.java:82) ~[?:1.16.4-53.1]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackListFromString(ItemStackUtil.java:132) ~[?:1.16.4-53.1]
	at vazkii.patchouli.common.util.ItemStackUtil.loadIngredientFromString(ItemStackUtil.java:109) ~[?:1.16.4-53.1]
	at vazkii.patchouli.client.book.template.variable.IngredientVariableSerializer.fromJson(IngredientVariableSerializer.java:13) ~[?:1.16.4-53.1]
	at vazkii.patchouli.client.book.template.variable.IngredientVariableSerializer.fromJson(IngredientVariableSerializer.java:10) ~[?:1.16.4-53.1]
	at vazkii.patchouli.client.book.template.variable.Variable.as(Variable.java:31) ~[?:1.16.4-53.1]
	at vazkii.patchouli.client.book.page.PageSpotlight.build(PageSpotlight.java:28) ~[?:1.16.4-53.1]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[?:1.16.4-53.1]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[?:1.16.4-53.1]
	... 65 more

**Comment by SatyrRex** [comment]
Ok, I just found this, as well: 
![Untitled](https://user-images.githubusercontent.com/20699503/131249551-de6e6c53-6fec-48ca-ba3c-c0c076356358.png)

**Comment by desht** [comment]
Ahh... toughasnails.  There's a page in the Heat entry which only loads if Tough As Nails is loaded.  But that was for the 1.12.2 Tough As Nails.  TAN is back in 1.16 but a cut-down version, without a lot of the mechanics.. including the Thermometer item, I'd guess.

I'll strip that page out completely for the next release since none of the TAN stuff is relevant to PNC in 1.16.

**Comment by desht** [comment]
Fixed in 2.14.3
